<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Views\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="MagicOnion.Client" Version="7.10.0" />
    <PackageReference Include="Microsoft.VisualStudio.Utilities" Version="17.14.40264" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GameServer\GameServer.csproj" />
  </ItemGroup>

</Project>
